- name: Remove old docker on all. 
  dnf: 
    name: 
    - docker
    - docker-client 
    - docker-client-latest 
    - docker-common
    - docker-latest 
    - docker-latest-logrotate 
    - docker-logrotate 
    - docker-engine
    state: absent
  become: true

- name: Check if docker-ce exists.
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_ce
  
- name: Add docker repository.
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo 
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true
  when: not docker_ce.stat.exists

- name: Install latest Docker. 
  dnf: 
    name: 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
  become: true

- name: Add docker user permissions.
  user:
    name: "{{ provision_ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Enable and start docker service.
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true

- name: install python package manager
  dnf:
    name: python3-pip
  become: true

- name: install python sdk
  # become_user: "{{ provision_ansible_user }}"
  pip:
    name:
      - pip
      - docker
      - docker-compose
  become: true