- name: Deploy Watchtower
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    command: --schedule "0 0 4 * * *" --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: unless-stopped

- name: Deploy portainer agent.
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    env:
      AGENT_SECRET: "{{ portainer_agent_secret }}"
    restart_policy: unless-stopped
