---
- hosts: all
  
  vars_files:
  - ./vars/encrypted-vars.yml
  - ./vars/unencrypted-vars.yml
  
  pre_tasks:
  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest
    become: true

  tasks:
    - import_tasks: tasks/docker.yml

- hosts: exitnodes

  vars_files:
    - ./vars/encrypted-vars.yml
    - ./vars/unencrypted-vars.yml

  tasks: 
    - import_tasks: tasks/exitnodes.yml 

- hosts: nodes

  vars_files:
    - ./vars/encrypted-vars.yml
    - ./vars/unencrypted-vars.yml

  tasks: 
    - import_tasks: tasks/nodes.yml 